name: Fusegroup
favicon: null
layout_spectrum: 0.09379
typography_spectrum: 0.80792
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7fa444'
    - '#e08c18'
    - '#1072af'
    - '#a6cbdf'
  brandStrength: 0.6215154293458909
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
